"""Independent stochastic ground-truth world model.

CRITICAL DESIGN INVARIANT:
This module defines how the simulator assigns latent recoverability to payments
and resolves action outcomes. It MUST remain entirely independent of:
  - recoveriq.policy (policy gate)
  - recoveriq.economics (EV engine)
  - recoveriq.model (probability model)
  - recoveriq.context (context extractor heuristics)
  - recoveriq.ai (AI layer)

The ground truth is NOT generated by RecoverIQ's logic. It is an independent
stochastic process that constitutes the synthetic "world" being evaluated.

Imports from this module:
  - simulation.schema (schema definitions only — no RecoverIQ decision logic)
  - simulation.config (configuration only)
  - Standard library (random)
"""

import random
from typing import Dict, Optional, Tuple

from recoveriq.domain.actions import Action
from recoveriq.domain.models import FailureCategory, CustomerTier
from recoveriq.simulation.schema import (
    GroundTruthRecord,
    RecoverabilityProfile,
    GROUND_TRUTH_RECOVERY_TABLE,
)


# Mapping from (FailureCategory, CustomerTier) to RecoverabilityProfile distribution.
# These weights are chosen to reflect plausible real-world recoverability patterns
# but are NOT derived from or equal to RecoverIQ's heuristics or model parameters.
#
# This is the world model's prior: hard declines are mostly unrecoverable,
# transient failures are more recoverable, VIP customers receive more attention.
_PROFILE_WEIGHTS: Dict[
    Tuple[FailureCategory, CustomerTier],
    Dict[RecoverabilityProfile, float],
] = {
    # Insufficient funds — recoverable if customer tops up
    (FailureCategory.INSUFFICIENT_FUNDS, CustomerTier.NEW): {
        RecoverabilityProfile.VERY_LOW: 0.15,
        RecoverabilityProfile.LOW: 0.35,
        RecoverabilityProfile.MEDIUM: 0.35,
        RecoverabilityProfile.HIGH: 0.12,
        RecoverabilityProfile.VERY_HIGH: 0.03,
    },
    (FailureCategory.INSUFFICIENT_FUNDS, CustomerTier.STANDARD): {
        RecoverabilityProfile.VERY_LOW: 0.10,
        RecoverabilityProfile.LOW: 0.25,
        RecoverabilityProfile.MEDIUM: 0.40,
        RecoverabilityProfile.HIGH: 0.20,
        RecoverabilityProfile.VERY_HIGH: 0.05,
    },
    (FailureCategory.INSUFFICIENT_FUNDS, CustomerTier.PREMIUM): {
        RecoverabilityProfile.VERY_LOW: 0.05,
        RecoverabilityProfile.LOW: 0.15,
        RecoverabilityProfile.MEDIUM: 0.40,
        RecoverabilityProfile.HIGH: 0.30,
        RecoverabilityProfile.VERY_HIGH: 0.10,
    },
    (FailureCategory.INSUFFICIENT_FUNDS, CustomerTier.VIP): {
        RecoverabilityProfile.VERY_LOW: 0.03,
        RecoverabilityProfile.LOW: 0.10,
        RecoverabilityProfile.MEDIUM: 0.30,
        RecoverabilityProfile.HIGH: 0.40,
        RecoverabilityProfile.VERY_HIGH: 0.17,
    },
    # Network timeout — mostly transient, highly recoverable
    (FailureCategory.NETWORK_TIMEOUT, CustomerTier.NEW): {
        RecoverabilityProfile.VERY_LOW: 0.05,
        RecoverabilityProfile.LOW: 0.15,
        RecoverabilityProfile.MEDIUM: 0.35,
        RecoverabilityProfile.HIGH: 0.35,
        RecoverabilityProfile.VERY_HIGH: 0.10,
    },
    (FailureCategory.NETWORK_TIMEOUT, CustomerTier.STANDARD): {
        RecoverabilityProfile.VERY_LOW: 0.03,
        RecoverabilityProfile.LOW: 0.10,
        RecoverabilityProfile.MEDIUM: 0.30,
        RecoverabilityProfile.HIGH: 0.40,
        RecoverabilityProfile.VERY_HIGH: 0.17,
    },
    (FailureCategory.NETWORK_TIMEOUT, CustomerTier.PREMIUM): {
        RecoverabilityProfile.VERY_LOW: 0.02,
        RecoverabilityProfile.LOW: 0.08,
        RecoverabilityProfile.MEDIUM: 0.25,
        RecoverabilityProfile.HIGH: 0.40,
        RecoverabilityProfile.VERY_HIGH: 0.25,
    },
    (FailureCategory.NETWORK_TIMEOUT, CustomerTier.VIP): {
        RecoverabilityProfile.VERY_LOW: 0.01,
        RecoverabilityProfile.LOW: 0.05,
        RecoverabilityProfile.MEDIUM: 0.20,
        RecoverabilityProfile.HIGH: 0.40,
        RecoverabilityProfile.VERY_HIGH: 0.34,
    },
    # Hard decline — mostly irrecoverable
    (FailureCategory.HARD_DECLINE, CustomerTier.NEW): {
        RecoverabilityProfile.VERY_LOW: 0.60,
        RecoverabilityProfile.LOW: 0.30,
        RecoverabilityProfile.MEDIUM: 0.08,
        RecoverabilityProfile.HIGH: 0.02,
        RecoverabilityProfile.VERY_HIGH: 0.00,
    },
    (FailureCategory.HARD_DECLINE, CustomerTier.STANDARD): {
        RecoverabilityProfile.VERY_LOW: 0.65,
        RecoverabilityProfile.LOW: 0.28,
        RecoverabilityProfile.MEDIUM: 0.06,
        RecoverabilityProfile.HIGH: 0.01,
        RecoverabilityProfile.VERY_HIGH: 0.00,
    },
    (FailureCategory.HARD_DECLINE, CustomerTier.PREMIUM): {
        RecoverabilityProfile.VERY_LOW: 0.60,
        RecoverabilityProfile.LOW: 0.30,
        RecoverabilityProfile.MEDIUM: 0.08,
        RecoverabilityProfile.HIGH: 0.02,
        RecoverabilityProfile.VERY_HIGH: 0.00,
    },
    (FailureCategory.HARD_DECLINE, CustomerTier.VIP): {
        RecoverabilityProfile.VERY_LOW: 0.55,
        RecoverabilityProfile.LOW: 0.32,
        RecoverabilityProfile.MEDIUM: 0.10,
        RecoverabilityProfile.HIGH: 0.03,
        RecoverabilityProfile.VERY_HIGH: 0.00,
    },
}

# Fallback distribution for any (category, tier) pair not explicitly listed above
_DEFAULT_PROFILE_WEIGHTS: Dict[RecoverabilityProfile, float] = {
    RecoverabilityProfile.VERY_LOW: 0.10,
    RecoverabilityProfile.LOW: 0.25,
    RecoverabilityProfile.MEDIUM: 0.40,
    RecoverabilityProfile.HIGH: 0.18,
    RecoverabilityProfile.VERY_HIGH: 0.07,
}


def _normalize(weights: Dict[RecoverabilityProfile, float]) -> Dict[RecoverabilityProfile, float]:
    """Return a normalized copy of a weight dict (sum -> 1.0)."""
    total = sum(weights.values())
    if total <= 0:
        raise ValueError("Profile weight distribution must have positive total weight.")
    return {k: v / total for k, v in weights.items()}


def _weighted_choice(
    rng: random.Random,
    weights: Dict[RecoverabilityProfile, float],
) -> RecoverabilityProfile:
    """Sample a RecoverabilityProfile according to a normalized weight dict."""
    profiles = list(weights.keys())
    probabilities = [weights[p] for p in profiles]
    return rng.choices(profiles, weights=probabilities, k=1)[0]


def assign_ground_truth(
    payment_id: str,
    failure_category: FailureCategory,
    customer_tier: CustomerTier,
    rng: random.Random,
) -> GroundTruthRecord:
    """Assign a latent RecoverabilityProfile and action probabilities to a payment.

    This is the world model's outcome assignment.  It is entirely independent
    of any RecoverIQ policy rule, heuristic, or probability estimate.

    Args:
        payment_id: Unique payment identifier.
        failure_category: Observed failure category.
        customer_tier: Customer tier.
        rng: Seeded random number generator (caller-provided for reproducibility).

    Returns:
        GroundTruthRecord with hidden recoverability data.
    """
    key = (failure_category, customer_tier)
    raw_weights = _PROFILE_WEIGHTS.get(key, _DEFAULT_PROFILE_WEIGHTS)
    normalized = _normalize(raw_weights)
    profile = _weighted_choice(rng, normalized)

    base_probs = dict(GROUND_TRUTH_RECOVERY_TABLE[profile])

    # Add a small stochastic perturbation per-payment to prevent trivial
    # deterministic patterns. The noise is small (±5%) and does not change the
    # overall profile rankings — it ensures that two payments with identical
    # observable features can have slightly different true outcomes.
    perturbed: Dict[Action, float] = {}
    for action, base_p in base_probs.items():
        # STOP action must always have probability 0.0 — no noise applied.
        # This is a domain invariant: STOP means no recovery attempt is made.
        if action == Action.STOP:
            perturbed[action] = 0.0
        else:
            noise = rng.uniform(-0.05, 0.05)
            perturbed[action] = max(0.0, min(1.0, base_p + noise))

    return GroundTruthRecord(
        payment_id=payment_id,
        latent_recoverability_profile=profile,
        action_base_probabilities=perturbed,
    )


def resolve_outcome(
    ground_truth: GroundTruthRecord,
    action: Action,
    rng: random.Random,
) -> bool:
    """Resolve whether a given action leads to successful recovery.

    Uses the world model's true action-conditioned probability.
    This is the ONLY place where a success/failure outcome is determined.

    Args:
        ground_truth: Hidden world-model record for this payment.
        action: The recovery action applied.
        rng: Seeded random number generator for reproducibility.

    Returns:
        True if the payment is recovered, False otherwise.
    """
    true_probability = ground_truth.action_base_probabilities.get(action, 0.0)
    return rng.random() < true_probability
